#Current Scraped Newsletters

all_newsletters = {
    "barbendnewsletter@mail2.barbend.com": "Barbend",
    "newsletter@mail.milkroad.com": "Milk Road",
    "investingjournal@mail.beehiiv.com": "Investing Journal",
    "general@mail.payloadspace.com": "Payload",
    "eventheodds@mail.beehiiv.com": "Even The Odds",
    "news@execsum.co": "Exec Sum",
    "press@shortsqueez.co": "Short Squeez",
    "theblueprint@mail.readtheblueprint.com": "The Blueprint",
    "news@newsletter.importantnotimportant.com": "Important Not Important",
    "news@thehustle.co": "The Hustle",
    "swaggystocks@mail.beehiiv.com": "Swaggy Stonks",
    "crew@morningbrew.com": "Morning Brew",
    "bensbites@mail.bensbites.co": "Ben's Bites",
    "Squad@thedailyupside.com": "The Daily Upside",
    "jeffs-bullseye@b.bullseyeoptiontrading.com": "Bullseye Trades",
    "newsletter@internationalintrigue.io": "International Intrigue",
    "invest@mail.beehiiv.com": "Digital Asset Investor",
    "blocmates@mail.beehiiv.com": "The Ape Enclosure",
    "wealth2@mail.beehiiv.com": "wealth^2",
    "joe@readthejoe.com": "The Average Joe",
    "sahil@sahilbloom.com": "Sahil Bloom's Curiosity Chronicle",
    "dailydough@mail.beehiiv.com": "Daily Dough",
    "moneyfittmorning@moneyfitt.co": "MoneyFitt Morning",
    "brian@brianferoldi.com": "Long-Term Mindset",
    "yolo@nftevening.com": "NFTevening",
    "hello@marketbriefs.com": "Market Briefs",
    "daily@chartr.co>": "Chartr",
}